##################################################################################################
# namespaces
##################################################################################################
apiVersion: v1
kind: Namespace
metadata:
    name: file-preview
    labels: 
      name: file-preview
---